apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: hawtio-oauth
  labels:
    app: hawtio
spec:
  type: NodePort
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 80
  selector:
    app: hawtio
